import json
import pycountry


data = {
        "Afghanistan": "Right Hand Traffic",
        "Albania": "Right Hand Traffic",
        "Algeria": "Right Hand Traffic",
        "Andorra": "Right Hand Traffic",
        "Angola": "Right Hand Traffic",
        "Antigua and Barbuda": "Left Hand Traffic",
        "Argentina": "Right Hand Traffic",
        "Armenia": "Right Hand Traffic",
        "Australia": "Left Hand Traffic",
        "Austria": "Right Hand Traffic",
        "Azerbaijan": "Right Hand Traffic",
        "The Bahamas": "Left Hand Traffic",
        "Bahrain": "Right Hand Traffic",
        "Bangladesh": "Left Hand Traffic",
        "Barbados": "Left Hand Traffic",
        "Belarus": "Right Hand Traffic",
        "Belgium": "Right Hand Traffic",
        "Belize": "Right Hand Traffic",
        "Benin": "Right Hand Traffic",
        "Bhutan": "Left Hand Traffic",
        "Bolivia": "Right Hand Traffic",
        "Bosnia and Herzegovina": "Right Hand Traffic",
        "Botswana": "Left Hand Traffic",
        "Brazil": "Right Hand Traffic",
        "Brunei": "Left Hand Traffic",
        "Bulgaria": "Right Hand Traffic",
        "Burkina Faso": "Right Hand Traffic",
        "Burundi": "Right Hand Traffic",
        "Cambodia": "Right Hand Traffic",
        "Cameroon": "Right Hand Traffic",
        "Canada": "Right Hand Traffic",
        "Cape Verde": "Right Hand Traffic",
        "Central African Republic": "Right Hand Traffic",
        "Chad": "Right Hand Traffic",
        "Chile": "Right Hand Traffic",
        "China": "Right Hand Traffic",
        "Hong Kong": "Left Hand Traffic",
        "Macao": "Left Hand Traffic",
        "Colombia": "Right Hand Traffic",
        "Comoros": "Right Hand Traffic",
        "Republic of Congo": "Right Hand Traffic",
        "Democratic Republic of the Congo": "Right Hand Traffic",
        "Costa Rica": "Right Hand Traffic",
        "Ivory Coast": "Right Hand Traffic",
        "Croatia": "Right Hand Traffic",
        "Cuba": "Right Hand Traffic",
        "Cyprus": "Left Hand Traffic",
        "Northern Cyprus": "Left Hand Traffic",
        "Czech Republic": "Right Hand Traffic",
        "Denmark": "Right Hand Traffic",
        "Djibouti": "Right Hand Traffic",
        "Dominica": "Left Hand Traffic",
        "Dominican Republic": "Right Hand Traffic",
        "East Timor": "Left Hand Traffic",
        "Ecuador": "Right Hand Traffic",
        "Egypt": "Right Hand Traffic",
        "El Salvador": "Right Hand Traffic",
        "Equatorial Guinea": "Right Hand Traffic",
        "Eritrea": "Right Hand Traffic",
        "Estonia": "Right Hand Traffic",
        "Eswatini": "Left Hand Traffic",
        "Ethiopia": "Right Hand Traffic",
        "Fiji": "Left Hand Traffic",
        "Finland": "Right Hand Traffic",
        "France": "Right Hand Traffic",
        "Gabon": "Right Hand Traffic",
        "Gambia": "Right Hand Traffic",
        "Georgia": "Right Hand Traffic",
        "Germany": "Right Hand Traffic",
        "Ghana": "Right Hand Traffic",
        "Greece": "Right Hand Traffic",
        "Grenada": "Left Hand Traffic",
        "Guatemala": "Right Hand Traffic",
        "Guinea": "Right Hand Traffic",
        "Guinea Bissau": "Right Hand Traffic",
        "Guyana": "Left Hand Traffic",
        "Haiti": "Right Hand Traffic",
        "Honduras": "Right Hand Traffic",
        "Hungary": "Right Hand Traffic",
        "Iceland": "Right Hand Traffic",
        "India": "Left Hand Traffic",
        "Indonesia": "Left Hand Traffic",
        "Iran": "Right Hand Traffic",
        "Iraq": "Right Hand Traffic",
        "Ireland": "Left Hand Traffic",
        "Israel": "Right Hand Traffic",
        "Italy": "Right Hand Traffic",
        "Jamaica": "Left Hand Traffic",
        "Japan": "Left Hand Traffic",
        "Jordan": "Right Hand Traffic",
        "Kazakhstan": "Right Hand Traffic",
        "Kenya": "Left Hand Traffic",
        "Kiribati": "Left Hand Traffic",
        "Kosovo": "Right Hand Traffic",
        "Kuwait": "Right Hand Traffic",
        "Kyrgyzstan": "Right Hand Traffic",
        "Laos": "Right Hand Traffic",
        "Latvia": "Right Hand Traffic",
        "Lebanon": "Right Hand Traffic",
        "Lesotho": "Left Hand Traffic",
        "Liberia": "Right Hand Traffic",
        "Libya": "Right Hand Traffic",
        "Liechtenstein": "Right Hand Traffic",
        "Lithuania": "Right Hand Traffic",
        "Luxembourg": "Right Hand Traffic",
        "Madagascar": "Right Hand Traffic",
        "Malawi": "Left Hand Traffic",
        "Malaysia": "Left Hand Traffic",
        "Maldives": "Left Hand Traffic",
        "Mali": "Right Hand Traffic",
        "Malta": "Left Hand Traffic",
        "Marshall Islands": "Right Hand Traffic",
        "Mauritania": "Right Hand Traffic",
        "Mauritius": "Left Hand Traffic",
        "Mexico": "Right Hand Traffic",
        "Federated States of Micronesia": "Right Hand Traffic",
        "Moldova": "Right Hand Traffic",
        "Monaco": "Right Hand Traffic",
        "Mongolia": "Right Hand Traffic",
        "Montenegro": "Right Hand Traffic",
        "Morocco": "Right Hand Traffic",
        "Mozambique": "Left Hand Traffic",
        "Myanmar": "Right Hand Traffic",
        "Namibia": "Left Hand Traffic",
        "Nauru": "Left Hand Traffic",
        "Nepal": "Left Hand Traffic",
        "Netherlands": "Right Hand Traffic",
        "New Zealand": "Left Hand Traffic",
        "Nicaragua": "Right Hand Traffic",
        "Niger": "Right Hand Traffic",
        "Nigeria": "Right Hand Traffic",
        "North Korea": "Right Hand Traffic",
        "North Macedonia": "Right Hand Traffic",
        "Norway": "Right Hand Traffic",
        "Oman": "Right Hand Traffic",
        "Pakistan": "Left Hand Traffic",
        "Palau": "Right Hand Traffic",
        "Palestine": "Right Hand Traffic",
        "Panama": "Right Hand Traffic",
        "Papua New Guinea": "Left Hand Traffic",
        "Paraguay": "Right Hand Traffic",
        "Peru": "Right Hand Traffic",
        "Philippines": "Right Hand Traffic",
        "Poland": "Right Hand Traffic",
        "Portugal": "Right Hand Traffic",
        "Qatar": "Right Hand Traffic",
        "Romania": "Right Hand Traffic",
        "Russia": "Right Hand Traffic",
        "Rwanda": "Right Hand Traffic",
        "Saint Kitts and Nevis": "Left Hand Traffic",
        "Saint Lucia": "Left Hand Traffic",
        "Saint Vincent and the Grenadines": "Left Hand Traffic",
        "Samoa": "Left Hand Traffic",
        "San Marino": "Right Hand Traffic",
        "Sao Tome and Principe": "Right Hand Traffic",
        "Saudi Arabia": "Right Hand Traffic",
        "Senegal": "Right Hand Traffic",
        "Serbia": "Right Hand Traffic",
        "Seychelles": "Left Hand Traffic",
        "Sierra Leone": "Right Hand Traffic",
        "Singapore": "Left Hand Traffic",
        "Slovakia": "Right Hand Traffic",
        "Slovenia": "Right Hand Traffic",
        "Solomon Islands": "Left Hand Traffic",
        "Somalia": "Right Hand Traffic",
        "Somaliland": "Right Hand Traffic",
        "South Africa": "Left Hand Traffic",
        "South Korea": "Right Hand Traffic",
        "South Sudan": "Right Hand Traffic",
        "Spain": "Right Hand Traffic",
        "Sri Lanka": "Left Hand Traffic",
        "Sudan": "Right Hand Traffic",
        "Suriname": "Left Hand Traffic",
        "Sweden": "Right Hand Traffic",
        "Switzerland": "Right Hand Traffic",
        "Syria": "Right Hand Traffic",
        "Taiwan": "Right Hand Traffic",
        "Tajikistan": "Right Hand Traffic",
        "Tanzania": "Left Hand Traffic",
        "Thailand": "Left Hand Traffic",
        "Togo": "Right Hand Traffic",
        "Tonga": "Left Hand Traffic",
        "Trinidad and Tobago": "Left Hand Traffic",
        "Tunisia": "Right Hand Traffic",
        "Turkey": "Right Hand Traffic",
        "Turkmenistan": "Right Hand Traffic",
        "Tuvalu": "Left Hand Traffic",
        "Uganda": "Left Hand Traffic",
        "Ukraine": "Right Hand Traffic",
        "United Arab Emirates": "Right Hand Traffic",
        "United Kingdom": "Left Hand Traffic",
        "British Indian Ocean Territory": "Right Hand Traffic",
        "British Virgin Islands": "Left Hand Traffic",
        "Cayman Islands": "Left Hand Traffic",
        "Falkland Islands": "Left Hand Traffic",
        "Gibraltar": "Right Hand Traffic",
        "Guernsey": "Left Hand Traffic",
        "Isle of Man": "Left Hand Traffic",
        "Jersey": "Left Hand Traffic",
        "Pitcairn Islands": "Left Hand Traffic",
        "Turks and Caicos Islands": "Left Hand Traffic",
        "United States": "Right Hand Traffic",
        "United States Virgin Islands": "Left Hand Traffic",
        "Northern Mariana Islands": "Right Hand Traffic",
        "Guam": "Right Hand Traffic",
        "Puerto Rico": "Right Hand Traffic",
        "American Samoa": "Right Hand Traffic",
        "Uruguay": "Right Hand Traffic",
        "Uzbekistan": "Right Hand Traffic",
        "Vanuatu": "Right Hand Traffic",
        "Vatican": "Right Hand Traffic",
        "Venezuela": "Right Hand Traffic",
        "Vietnam": "Right Hand Traffic",
        "Western Sahara": "Right Hand Traffic",
        "Yemen": "Right Hand Traffic",
        "Zambia": "Left Hand Traffic",
        "Zimbabwe": "Left Hand Traffic",
        "Greenland": "Right Hand Traffic",
        "Faroe Islands": "Right Hand Traffic",
        "Bermuda": "Left Hand Traffic",
        "Saint Pierre and Miquelon": "Right Hand Traffic",
        "Aland": "Right Hand Traffic",
        "Saint Helena": "Left Hand Traffic",
        "Reunion": "Right Hand Traffic",
        "Cocos Islands": "Left Hand Traffic",
        "Christmas Island": "Left Hand Traffic",
        "French Southern and Antarctic Lands": "Right Hand Traffic",
        "Heard Island and McDonald Islands": "Left Hand Traffic",
        "Norfolk Island": "Left Hand Traffic",
        "New Caledonia": "Right Hand Traffic",
        "United States Minor Outlying Islands": "Right Hand Traffic",
        "Anguilla": "Left Hand Traffic",
        "Saint Martin": "Right Hand Traffic",
        "Sint Maarten": "Right Hand Traffic",
        "Saint Barthelemy": "Right Hand Traffic",
        "Montserrat": "Left Hand Traffic",
        "Martinique": "Right Hand Traffic",
        "Aruba": "Right Hand Traffic",
        "Curaçao": "Right Hand Traffic",
        "South Georgia and South Sandwich Islands": "Left Hand Traffic",
        "Midway Atoll": "Right Hand Traffic",
        "Wallis and Futuna": "Right Hand Traffic",
        "Niue": "Left Hand Traffic",
        "Cook Islands": "Left Hand Traffic",
        "French Polynesia": "Right Hand Traffic"}

# Function to convert country names to ISO Alpha-2 codes
def country_to_alpha2(country_name):
    try:
        country = pycountry.countries.lookup(country_name)
        return country.alpha_2
    except LookupError:
        return None  # Return None if the country name is not found

# Create a new dictionary with ISO Alpha-2 country codes
updated_data = {}

for country, coverage in data.items():
    country_code = country_to_alpha2(country)
    if country_code:  # Only add if the country code is found
        updated_data[country_code] = "L" if coverage == "Left Hand Traffic" else "R"
    else:
        print(f"Warning: Could not find country code for {country}")

# Save the updated data to a new JSON file
with open('drivingside.json', 'w', encoding='utf-8') as output_file:
    json.dump(updated_data, output_file, indent=4)

print("Data successfully written to output.json")

